### ISSUE TITLE
Cannot start app

### ISSUE THREAD

**Issue by vendelieu** [ddimaria/rust-actix-example#7]
thread 'main' panicked at 'Configuration Error: Custom(
    "invalid digit found in string while parsing value \'short\' provided by RUST_BACKTRACE",
)', src/config.rs:43:23

```
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:328
  13: rust_actix_example::config::get_config
             at src/config.rs:43
  14: <rust_actix_example::config::CONFIG as core::ops::deref::Deref>::deref::__static_ref_initialize
             at src/config.rs:34
  15: core::ops::function::FnOnce::call_once
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/ops/function.rs:227
  16: lazy_static::lazy::Lazy<T>::get::{{closure}}
             at /home/venny/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/inline_lazy.rs:31
  17: std::sync::once::Once::call_once::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/sync/once.rs:224
  18: std::sync::once::Once::call_inner
             at src/libstd/sync/once.rs:391
  19: std::sync::once::Once::call_once
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/sync/once.rs:224
  20: lazy_static::lazy::Lazy<T>::get
             at /home/venny/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/inline_lazy.rs:30
  21: <rust_actix_example::config::CONFIG as core::ops::deref::Deref>::deref::__stability
             at ./<::lazy_static::__lazy_static_internal macros>:16
  22: <rust_actix_example::config::CONFIG as core::ops::deref::Deref>::deref
             at ./<::lazy_static::__lazy_static_internal macros>:18
  23: rust_actix_example::server::server::{{closure}}
             at src/server.rs:37
  24: <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/future.rs:43
  25: std::future::set_task_context
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/future.rs:79
  26: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/future.rs:43
  27: std::future::poll_with_tls_context::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/future.rs:121
  28: std::future::get_task_context
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/future.rs:111
  29: std::future::poll_with_tls_context
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/future.rs:121
  30: rust_actix_example::main::{{closure}}
             at src/main.rs:33
  31: <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/future.rs:43
  32: std::future::set_task_context
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/future.rs:79
  33: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/future.rs:43
  34: <tokio::task::local::LocalFuture<F> as core::future::future::Future>::poll::{{closure}}
             at /home/venny/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/task/local.rs:403
  35: tokio::task::local::Scheduler::with::{{closure}}
             at /home/venny/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/task/local.rs:478
  36: std::thread::local::LocalKey<T>::try_with
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/local.rs:262
  37: std::thread::local::LocalKey<T>::with
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/local.rs:239
  38: tokio::task::local::Scheduler::with
             at /home/venny/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/task/local.rs:474
  39: <tokio::task::local::LocalFuture<F> as core::future::future::Future>::poll
             at /home/venny/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/task/local.rs:402
  40: std::future::poll_with_tls_context::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/future.rs:121
  41: std::future::get_task_context
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/future.rs:111
  42: std::future::poll_with_tls_context
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/future.rs:121
  43: tokio::task::local::LocalSet::run_until::{{closure}}
             at /home/venny/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/task/local.rs:358
  44: <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/future.rs:43
  45: std::future::set_task_context
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/future.rs:79
  46: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/future.rs:43
  47: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /home/venny/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/basic_scheduler.rs:138
  48: tokio::runtime::Runtime::block_on::{{closure}}
             at /home/venny/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/mod.rs:411
  49: tokio::runtime::context::enter
             at /home/venny/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/context.rs:72
  50: tokio::runtime::handle::Handle::enter
             at /home/venny/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/handle.rs:34
  51: tokio::runtime::Runtime::block_on
             at /home/venny/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/mod.rs:408
  52: tokio::task::local::LocalSet::block_on
             at /home/venny/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/task/local.rs:321
  53: actix_rt::runtime::Runtime::block_on
             at /home/venny/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.0.0/src/runtime.rs:89
  54: actix_rt::builder::SystemRunner::block_on
             at /home/venny/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.0.0/src/builder.rs:187
  55: rust_actix_example::main
             at src/main.rs:31
  56: std::rt::lang_start::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  57: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  58: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  59: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  60: std::panicking::try
             at src/libstd/panicking.rs:265
  61: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  62: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  63: std::rt::lang_start
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  64: main
  65: __libc_start_main
  66: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic in Arbiter thread.

Process finished with exit code 101
```

**Comment by najeeb-aai** [comment]
any solution for this?
